### ISSUE TITLE
Testing email adress blackhole@onionmx.org bounces when connecting through transparent tor setup

### ISSUE THREAD

**Issue by gizahNL** [ehloonion/onionrouter#12]
Running FreeBSD, since it has proven impossible to get the suggested setup working with the smtp_tor script `postfix 3.2.3, '/usr/local/libexec/postfix/smtp_tor: bad command startup -- throttling' `
I've setup a transparent tor system with my OpenBSD firewall diverting through tor transport. 

Sending a test mail to blackhole@onionmx.org results in the same 550 reject as when connecting clearnet. Study of logs does show connecting through tor (10.192.0.0/11 are tormapped adresses):
```
Oct 12 21:01:55 mailserv postfix/smtp[46156]: 384483B1AF: to=<blackhole@onionmx.org>, relay=127.0.0.1[127.0.0.1]:10026, delay=6.8, delays=0.15/0.02/0/6.7, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10027): 250 2.0.0 Ok: queued as C4F8A3B1B8)
Oct 12 21:01:55 mailserv postfix/qmgr[46127]: 384483B1AF: removed
Oct 12 21:01:55 mailserv postfix/smtp[46170]: Host offered STARTTLS: [ysp4gfuhnmj6b4mb.onion]
Oct 12 21:01:55 mailserv postfix/smtp[46170]: C4F8A3B1B8: to=<blackhole@onionmx.org>, relay=ysp4gfuhnmj6b4mb.onion[10.214.246.181]:25, delay=1.1, delays=0.22/0.03/0.61/0.19, dsn=5.0.0, status=bounced (host ysp4gfuhnmj6b4mb.onion[10.214.246.181] said: 550 blackhole@onionmx.org is only available through onionmx (in reply to RCPT TO command))
Oct 12 21:01:56 mailserv postfix/cleanup[46155]: 00E5D3B1BA: message-id=<20171012190156.00E5D3B1BA@smtp.heteigenwijsje.nl>

```
Though obviously I already know that my setup is working it might be nice for others who would go for a similar setup to have a working testing solution ;) 
Even nicer would be an automatic reply on the adres to check if the system also correctly receives mail ;) 

Can confirm that onionrouter script is working on FreeBSD 10.3 with python2.7

**Comment by gizahNL** [comment]
here's a sample, probably badly written (not a coder/scripwriter), rc.d script useable on FreeBSD (starts correctly, stop command doesn't work due to pidfile containing #) 

```
#!/bin/sh
# PROVIDE: onionrouter
# REQUIRE: LOGIN 
# BEFORE: mail
# KEYWORD: shutdown


. /etc/rc.subr

name=onionrouter
start_cmd="${name}_start"
rcvar=onionrouter_enable
pidfile=/var/run/onionrouter.pid
: ${onionrouter_enable:=no}
: ${onionrouter_config="/usr/local/etc/onionrouter/config.ini"}
: ${onionrouter_map="/usr/local/etc/onionrouter/map.yml"}
: ${onionrouter_flags=""}

onionrouter_start()
{	
/usr/sbin/daemon -P ${pidfile} /usr/local/onionrouter/onionrouter_run --config ${onionrouter_config} --mappings ${onionrouter_map} ${onionrouter_flags}
}

load_rc_config $name
run_rc_command "$1"
```

**Comment by kargig** [comment]
1) Are you sure /usr/local/libexec/postfix/smtp_tor is executable and contains a proper shebang line ?

2) I can confirm that currently "blackhole@onionmx.org" doesn't work as expected. It has been reported to the owners of onionmx.org and it should get fixed soon. Thanks for reporting. 

3) If you want to submit your script please open a PR.

Please open different issues for each topic in the future.

**Comment by kargig** [comment]
Issue referenced in the title seems solved right now, so I'm going to close it.

Please open separate issues for the rest if you want.

Thanks!
